# Exported from Render on 2024-06-08T18:04:59Z
databases:
- name: bite_speed
  databaseName: bite_speed_07b6
  user: bite_speed_07b6_user
  plan: free
  region: oregon
  ipAllowList:
  - source: 0.0.0.0/0
    description: everywhere
  postgresMajorVersion: "16"
version: "1"
