development:
  adapter: postgresql
  database: bitespeed_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: bitespeed_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: bitespeed_production
  pool: 5
  timeout: 5000
  url: <%= ENV['DATABASE_URL'] %>
  username: root
  password: <%= ENV['MYSITE_DATABASE_PASSWORD'] %>
